# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket  = "terraform-state-387859"
    encrypt = true
    key     = "k8s/terraform.tfstate"
    region  = "us-east-2"
  }
}
